[Sun Oct 28 16:58:34.222334 2018] [mpm_worker:notice] [pid 62278:tid 140607525963648] AH00298: SIGHUP received.  Attempting to restart
[Sun Oct 28 16:58:34.322721 2018] [mpm_worker:notice] [pid 62278:tid 140607525963648] AH00292: Apache/2.4.33 (Unix) mod_wsgi/4.6.4 Python/3.5 configured -- resuming normal operations
[Sun Oct 28 16:58:34.322740 2018] [core:notice] [pid 62278:tid 140607525963648] AH00094: Command line: '/home/deev/webapps/fvt/apache2/bin/httpd.worker -f /home/deev/webapps/fvt/apache2/conf/httpd.conf'
[Sun Oct 28 17:01:23.959273 2018] [mpm_worker:notice] [pid 62278:tid 140607525963648] AH00298: SIGHUP received.  Attempting to restart
[Sun Oct 28 17:01:24.063060 2018] [mpm_worker:notice] [pid 62278:tid 140607525963648] AH00292: Apache/2.4.33 (Unix) mod_wsgi/4.6.4 Python/3.5 configured -- resuming normal operations
[Sun Oct 28 17:01:24.063107 2018] [core:notice] [pid 62278:tid 140607525963648] AH00094: Command line: '/home/deev/webapps/fvt/apache2/bin/httpd.worker -f /home/deev/webapps/fvt/apache2/conf/httpd.conf'
[Sun Oct 28 17:03:52.123140 2018] [mpm_worker:notice] [pid 62278:tid 140607525963648] AH00298: SIGHUP received.  Attempting to restart
[Sun Oct 28 17:03:52.240759 2018] [mpm_worker:notice] [pid 62278:tid 140607525963648] AH00292: Apache/2.4.33 (Unix) mod_wsgi/4.6.4 Python/3.5 configured -- resuming normal operations
[Sun Oct 28 17:03:52.240781 2018] [core:notice] [pid 62278:tid 140607525963648] AH00094: Command line: '/home/deev/webapps/fvt/apache2/bin/httpd.worker -f /home/deev/webapps/fvt/apache2/conf/httpd.conf'
[Sun Oct 28 17:03:55.564971 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020] mod_wsgi (pid=54487): Failed to exec Python script file '/home/deev/webapps/fvt/htdocs/index.py'.
[Sun Oct 28 17:03:55.565041 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020] mod_wsgi (pid=54487): Exception occurred processing WSGI script '/home/deev/webapps/fvt/htdocs/index.py'.
[Sun Oct 28 17:03:55.565536 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020] Traceback (most recent call last):
[Sun Oct 28 17:03:55.565566 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020]   File "/home/deev/webapps/fvt/htdocs/index.py", line 11, in <module>
[Sun Oct 28 17:03:55.565571 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020]     from fvt.fvt import app as application
[Sun Oct 28 17:03:55.565577 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020]   File "/home/deev/webapps/fvt/htdocs/fvt/fvt.py", line 4, in <module>
[Sun Oct 28 17:03:55.565580 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020]     from . helpers import newRandomVerb, checkVerb
[Sun Oct 28 17:03:55.565596 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020]   File "/home/deev/webapps/fvt/htdocs/fvt/helpers.py", line 206
[Sun Oct 28 17:03:55.565604 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020]     return jsonify("status": "ok", "data": data)
[Sun Oct 28 17:03:55.565628 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020]                            ^
[Sun Oct 28 17:03:55.565636 2018] [wsgi:error] [pid 54487:tid 140607339800320] [remote 127.0.0.1:59020] SyntaxError: invalid syntax
